import { EditorView } from "@codemirror/view";

export const livePreviewTheme = EditorView.baseTheme({
  ".cm-hive-preview-strong": { fontWeight: "700" },
  ".cm-hive-preview-emphasis": { fontStyle: "italic" },
  ".cm-hive-preview-strikethrough": { textDecoration: "line-through" },
  ".cm-hive-preview-inline-code": {
    padding: "0 0.2em",
    borderRadius: "2px",
    backgroundColor: "#2a2a2a",
    color: "#e5c786",
    fontFamily: "var(--mono-font)",
    fontSize: "0.94em",
  },
  ".cm-hive-preview-heading": {
    display: "inline-block",
    width: "100%",
    margin: "0.65em 0 0.2em",
    lineHeight: "1.2",
    fontWeight: "700",
  },
  // CodeMirror's default highlight style underlines headings; live preview shows them by size only.
  ".cm-hive-preview-heading, .cm-hive-preview-heading *": { textDecoration: "none !important" },
  ".cm-hive-preview-heading-1": { fontSize: "1.35em" },
  ".cm-hive-preview-heading-2": { fontSize: "1.2em" },
  ".cm-hive-preview-heading-3": { fontSize: "1.1em" },
  ".cm-hive-preview-heading-4, .cm-hive-preview-heading-5, .cm-hive-preview-heading-6": { fontSize: "1em" },
  ".cm-hive-preview-bullet": { display: "inline-block", width: "1.25em", textAlign: "center", color: "var(--text-dim)" },
  ".cm-hive-preview-ordered-marker": { color: "var(--text-dim)" },
  ".cm-hive-preview-task-done": { color: "var(--text-dim)", textDecoration: "line-through" },
  ".cm-hive-preview-checkbox": {
    display: "inline-flex",
    width: "0.92em",
    height: "0.92em",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "0.45em",
    border: "1px solid #8c8c8c",
    borderRadius: "2px",
    verticalAlign: "-0.08em",
    boxSizing: "border-box",
    lineHeight: "1",
    userSelect: "none",
    cursor: "pointer",
  },
  ".cm-hive-preview-checkbox.is-checked": { borderColor: "var(--accent)", backgroundColor: "var(--accent)" },
  ".cm-hive-preview-checkbox.is-checked::after": { content: "'✓'", color: "#181818", fontSize: "0.8em", fontWeight: "700", lineHeight: "1" },
  ".cm-hive-preview-blockquote": { color: "var(--text-dim)" },
  ".cm-hive-preview-quote-mark": { display: "inline-block", width: "1.2em", color: "var(--text-dim)" },
  ".cm-hive-preview-code-block": {
    display: "inline-block",
    width: "100%",
    boxSizing: "border-box",
    padding: "0 0.35em",
    backgroundColor: "#1c1c1c",
    color: "#e5c786",
    fontFamily: "var(--mono-font)",
    fontSize: "0.94em",
    lineHeight: "1.45",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  ".cm-hive-preview-hr": { display: "block", width: "100%", borderTop: "1px solid #555", margin: "0.65em 0" },
});
